// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gqYfaAAQgiNFGqC6UaDBwRcwPaH8TFk',
    appId: '1:572346457102:web:fc89e15baecba15c6ab05f',
    messagingSenderId: '572346457102',
    projectId: 'dotillos-attendance',
    authDomain: 'dotillos-attendance.firebaseapp.com',
    storageBucket: 'dotillos-attendance.appspot.com',
    measurementId: 'G-9TTBKJY8RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhQ8JC-aZtoo-uq_okGntUI5qhEobxSw',
    appId: '1:572346457102:android:baa7ca962bd761556ab05f',
    messagingSenderId: '572346457102',
    projectId: 'dotillos-attendance',
    storageBucket: 'dotillos-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalTQvRAZLW28RpkK83QYkkM4S8B2urqE',
    appId: '1:572346457102:ios:57ff786e7577e4746ab05f',
    messagingSenderId: '572346457102',
    projectId: 'dotillos-attendance',
    storageBucket: 'dotillos-attendance.appspot.com',
    iosClientId: '572346457102-eduga1q4stsll7nf0va17qv4c7jbqabq.apps.googleusercontent.com',
    iosBundleId: 'com.qrattendance.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBalTQvRAZLW28RpkK83QYkkM4S8B2urqE',
    appId: '1:572346457102:ios:57ff786e7577e4746ab05f',
    messagingSenderId: '572346457102',
    projectId: 'dotillos-attendance',
    storageBucket: 'dotillos-attendance.appspot.com',
    iosClientId: '572346457102-eduga1q4stsll7nf0va17qv4c7jbqabq.apps.googleusercontent.com',
    iosBundleId: 'com.qrattendance.attendance',
  );
}
